### ISSUE TITLE
No documentation on install, and install.sh fails

### ISSUE THREAD

**Issue by n7ekg** [BernardoGiordano/signal-desktop-pi4#5]
pi@raspberrypi:/usr/local/src/signal-desktop-pi4 $ sh ./install.sh 
installing apt dependencies...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-is-python3
E: Unable to locate package libcrypto++8
E: Couldn't find any package by regex 'libcrypto++8'

**Comment by BernardoGiordano** [comment]
There are no information on your environment. Closing, feel free to open another issue when you provide context
